parameters:
  - name: semver
    type: string

stages:
  - stage: validation
    jobs:
      - job: validation
        steps:
          - script: |
              echo "semver: ${{ parameters.semver }}"

              if ! [[ "${{ parameters.semver }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$ ]]; then
                echo "SemVer is invalid"
                exit 1
              fi
            displayName: 'Check semver is valid'
