trigger: none

parameters:
  - name: semver
    type: string

pool:
  name: Cloud-bcz-pub

stages:
  - template: .azure-pipelines/steps/azure-pipelines-semver.yml
    parameters:
      semver: ${{ parameters.semver }}

  - template: .azure-pipelines/steps/azure-pipelines-build.yml

  - template: .azure-pipelines/steps/azure-pipelines-deploy-stage.yml
    parameters:
      deploymentStages:
        - deployEnv: 'e6'
